### ISSUE TITLE
Openseamap overlay

### ISSUE THREAD

**Issue by benoit-jpi** [kalisio/kano#143]
Hello, there would be an interest in making an openseamap layer available in kano. This overlay layer adds sea marks (cardinal or lateral marks or other aids to navigation, buoy or fixed structure) in coastal waters.

service available at https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png

**Comment by claustres** [comment]
As it is a standard XYZ layer it can be easily added, the OSM layer can be used as a [model](https://github.com/kalisio/kano/blob/master/api/config/layers/background-layers.js#L3). 

However, although [data licensing](http://www.openseamap.org/index.php?id=faq&L=1) is pretty clear the right to use the tile server in a third-party product is not mentioned. Not sure if it's a good idea to add it by default then, will ask them about it.

**Comment by claustres** [comment]
Actually, now there are no default layers when deploying Kano unless specified by `LAYERS_FILTER`, so we could add it anyway and people can select it if they want. 

:pray: PR is welcome, initialize a `marine-layers.js` in the :open_file_folder:  [config/layers]( https://github.com/kalisio/kano/tree/master/api/config/layers) folder.
