### ISSUE TITLE
Switching from 2D to 3D activity if a GeoJson layer is visible raises an error

### ISSUE THREAD

**Issue by claustres** [kalisio/kano#169]
The following error is raised when switching from 2D to 3D activity if a GeoJson layer has been imported and is visible: `TypeError: Cannot read property 'features' of undefined`. 

Linked to https://github.com/kalisio/kdk/issues/328.

**Comment by robinbourianes-kalisio** [comment]
What happens is destroyed gets called from [mixin.base-map](https://github.com/kalisio/kdk/blob/2bb0ab8432820c1a71cdc095d1ec2d856cdaa22b/map/client/mixins/map/mixin.base-map.js#L388) which calls this.map.remove()
this.map.remove() iterate over it's layer [calling remove() on them](https://github.com/Leaflet/Leaflet/blob/32ea41baaa93adcefd34006a12ebe3b4ee7fda7d/src/map/Map.js#L782)
Realtime layer's [remove method](https://github.com/perliedman/leaflet-realtime/blob/c8bfd48335dbb5fb418252584c0e9e9565f54276/src/L.Realtime.js#L114) expects a geojson parameter which is then undefined, generating an exception.

We probably should clear the map before this.map.remove() in mixin.base-map destroyed.

**Comment by robinbourianes-kalisio** [comment]
The layer on which the error occurs is the selection layer that is added by mixin.feature-selection

**Comment by claustres** [comment]
Right, the issue has been identified in https://github.com/kalisio/kdk/issues/328, waiting for maintainer feedback.

What is strange is that the map should have been already cleaned [here](https://github.com/kalisio/kdk/blob/master/map/client/mixins/map/mixin.base-map.js#L383) but it seems it is still referenced in Leaflet.

**Comment by claustres** [comment]
Seems to be closed now, possibly linked to https://github.com/kalisio/kdk/issues/328.
