### ISSUE TITLE
WebGL based weather layers are not rendered on mobile devices

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kano#185]

**Comment by robinbourianes-kalisio** [comment]
Tracking down the issue, it seems it's because our version of pixi (5.0.4) prefers a webgl1 context on non apple mobile devices: see https://github.com/pixijs/pixijs/blob/v5.0.4/packages/core/src/settings.js#L12

**Comment by robinbourianes-kalisio** [comment]
The bug report the pixi code refers to has been fixed around april 2019 so I think we should override this settings and allow webgl2 on mobile devices too now.

**Comment by robinbourianes-kalisio** [comment]
Seems to work now at least with latest firefox & chrome on an android phone.
@cnouguier which browser were you using using when you noticed the bug ? Could you test on your side too ?
