### ISSUE TITLE
Y axis for precipitations exhibit a negative scale in timeseries widget

### ISSUE THREAD

**Issue by claustres** [kalisio/kano#199]
As precipitations are always >= 0 the axis should start at 0.

**Comment by benoit-jpi** [comment]
How to reproduce the behavior : The "pipette" tool is activated to pick values on the map and visualize the forecasts at that point. When the precipitations are equal to 0 over the entire period, then the scale adapts itself between -1 mm and + 1mm. When the precipitation is non-zero at one or more instants of the period, then the scale adapts itself correctly and the minimum value of the ordinate is 0.

**Comment by claustres** [comment]
Thanks for this detailed description, it should be fixed in the next release.
