### ISSUE TITLE
Allow to display meteorological radar data

### ISSUE THREAD

**Issue by claustres** [kalisio/kano#21]
Linked to https://github.com/kalisio/kMap/issues/31 & https://github.com/kalisio/kargo/issues/11.

**Comment by cnouguier** [comment]
Here is an example of a GDAL script to apply on the source raster to simplify the visualization process: 

```
for %%f in (*.tif) do (
  # Transform the dataset in GEO WGS84
  gdalwarp -t_srs EPSG:4326 %%f output/WGS84_%%f
  # Extract the 2nd band
  gdal_translate -b 2 -co COMPRESS=LZW output/WGS84_%%f output/b2_%%f
  # Extract the 3th band
  gdal_translate -b 3 -co COMPRESS=LZW output/WGS84_%%f output/b3_%%f
)
```

LZW compression ensure to have an optimized raster that could be exposed using thredds

**Comment by claustres** [comment]
Waiting to be able to connect to Meteo France servers to download radar data in Thredds.
