### ISSUE TITLE
Switching between forecast models can break the timeline

### ISSUE THREAD

**Issue by claustres** [kalisio/kano#24]
On the deployed version https://kano.irsn.kalisio.xyz/#/home/map?south=29.15216128331894&west=-60.77636718750001&north=58.790978406215565&east=23.598632812500004 select a date at least 3 days after current time, then switch the forecast model to AROME, which has a small range, the timeline overflow the screen.

**Comment by leob** [comment]
I'll have a look at this.

**Comment by leob** [comment]
I was now finally able to reproduce this. Looks like the "overflow" problem is related to the way I calculate the size of the "intervals", now looking at this.

**Comment by leob** [comment]
This should be fixed now, I've pushed a corrected version of MapActivity.vue (git commit 8bc8a47 in the kano repo).

**Comment by leob** [comment]
Closing this now
