### ISSUE TITLE
The legend has an orientation depending on the displayed layer

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kano#40]
It seems that the orientation of the legend is depending from the domain of the chroma object provided by the current displayed layer. As chroma provides the capability to invert a domain, the legend orientation is also inverted.
It should be always oriented from bottom to top with the lowest value of the domain at the bottom and the highest value at the top.

**Comment by leob** [comment]
This should be fixed now, I've pushed a corrected version of KColorLegend.vue (git commit 6a60630 in the kMap repo).

**Comment by leob** [comment]
Closing this now
